//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KulujenSeuranta.Resources.Views.Home.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments ».
        /// </summary>
        public static string btnPayments {
            get {
                return ResourceManager.GetString("btnPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics ».
        /// </summary>
        public static string btnStatistics1 {
            get {
                return ResourceManager.GetString("btnStatistics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics ».
        /// </summary>
        public static string btnStatistics2 {
            get {
                return ResourceManager.GetString("btnStatistics2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Management is application for managing your payments..
        /// </summary>
        public static string txtAppDefinition {
            get {
                return ResourceManager.GetString("txtAppDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Management application.
        /// </summary>
        public static string txtAppName {
            get {
                return ResourceManager.GetString("txtAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string txtPageTitle {
            get {
                return ResourceManager.GetString("txtPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments definition ....
        /// </summary>
        public static string txtPaymentsDefinition {
            get {
                return ResourceManager.GetString("txtPaymentsDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string txtPaymentsHeading {
            get {
                return ResourceManager.GetString("txtPaymentsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics 2 definition ....
        /// </summary>
        public static string txtStatistics2Definition {
            get {
                return ResourceManager.GetString("txtStatistics2Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics 2.
        /// </summary>
        public static string txtStatistics2Heading {
            get {
                return ResourceManager.GetString("txtStatistics2Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics 1 definition ... .
        /// </summary>
        public static string txtStatisticsDefinition {
            get {
                return ResourceManager.GetString("txtStatisticsDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satistics 1.
        /// </summary>
        public static string txtStatisticsHeading {
            get {
                return ResourceManager.GetString("txtStatisticsHeading", resourceCulture);
            }
        }
    }
}
