// <auto-generated />
namespace KulujenSeuranta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BaseEntity_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseEntity_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201409020715222_BaseEntity_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
